### ISSUE TITLE
User Activity dashboard error (2.3.2)

### ISSUE THREAD

**Issue by green17** [ryssbowh/craft-activity#10]
We are using Craft Craft Pro 4.3.4 and recently upgraded to Craft Activity 2.3.2 in order to use the new user full name feature. After the upgrade, everything looked to be working well but unfortunately we have started to get the below error when trying to access the Craft Activity dashboard.

`yii\base\ErrorException: Array to string conversion in website.com/vendor/twig/twig/src/Extension/CoreExtension.php:730
Stack trace:
#0 website.com/vendor/craftcms/cms/src/web/ErrorHandler.php(79): yii\base\ErrorHandler->handleError()
#1 [internal function]: craft\web\ErrorHandler->handleError()
#2 website.com/vendor/twig/twig/src/Extension/CoreExtension.php(730): implode()
#3 website.com/storage/runtime/compiled_templates/64/64814cdc28f86fabc852f7ae9f7acad3.php(272): twig_join_filter()
#4 website.com/vendor/twig/twig/src/Extension/CoreExtension.php(1202): __TwigTemplate_5aa687d46d67f57367f0220064fb987b->macro_elementValue()
#5 website.com/storage/runtime/compiled_templates/64/64814cdc28f86fabc852f7ae9f7acad3.php(338): twig_call_macro()
#6 website.com/vendor/twig/twig/src/Extension/CoreExtension.php(1202): __TwigTemplate_5aa687d46d67f57367f0220064fb987b->macro_elementFromValue()
#7 website.com/storage/runtime/compiled_templates/64/64814cdc28f86fabc852f7ae9f7acad3.php(412): twig_call_macro()
#8 website.com/vendor/twig/twig/src/Extension/CoreExtension.php(1202): __TwigTemplate_5aa687d46d67f57367f0220064fb987b->macro_elementField()
#9 website.com/storage/runtime/compiled_templates/6e/6e88cdfa046fd225d22720e96c08cf27.php(132): twig_call_macro()
#10 website.com/vendor/twig/twig/src/Template.php(394): __TwigTemplate_1890adb904c51a0d47c2b9fe0f031439->doDisplay()
#11 website.com/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#12 website.com/storage/runtime/compiled_templates/64/64814cdc28f86fabc852f7ae9f7acad3.php(372): Twig\Template->display()
#13 website.com/vendor/twig/twig/src/Extension/CoreExtension.php(1202): __TwigTemplate_5aa687d46d67f57367f0220064fb987b->macro_elementField()
#14 website.com/storage/runtime/compiled_templates/74/74a3811f989cfacfc864c162a586b505.php(53): twig_call_macro()
#15 website.com/vendor/twig/twig/src/Template.php(394): __TwigTemplate_c8217b99fc8d6ef5561360914a88f719->doDisplay()
#16 website.com/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#17 website.com/vendor/twig/twig/src/Template.php(379): Twig\Template->display()
#18 website.com/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render()
#19 website.com/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render()
#20 website.com/vendor/craftcms/cms/src/web/View.php(451): Twig\Environment->render()
#21 website.com/vendor/ryssbowh/craft-activity/src/base/logs/ElementLog.php(35): craft\web\View->renderTemplate()
#22 website.com/vendor/yiisoft/yii2/base/Component.php(139): Ryssbowh\Activity\base\logs\ElementLog->getDescription()
#23 website.com/vendor/craftcms/cms/src/helpers/Template.php(99): yii\base\Component->__get()
#24 website.com/storage/runtime/compiled_templates/49/491e83fd4a803cd660e91b94069f1ac0.php(43): craft\helpers\Template::attribute()
#25 website.com/vendor/twig/twig/src/Template.php(394): __TwigTemplate_c1af15399399c1023514a30a39c21933->doDisplay()
#26 website.com/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#27 website.com/storage/runtime/compiled_templates/0c/0c5d3db4539362a4f5206d5e01455e22.php(343): Twig\Template->display()
#28 website.com/vendor/twig/twig/src/Template.php(171): __TwigTemplate_5492fdda9b1f59d9d8e189b3225714cb->block_content()
#29 website.com/storage/runtime/compiled_templates/24/243e511257f7779fdec8595e74f3c3a7.php(590): Twig\Template->displayBlock()
#30 website.com/vendor/twig/twig/src/Template.php(171): __TwigTemplate_2ca8fd43835316cf29a72e0b834d2972->block_main()
#31 website.com/storage/runtime/compiled_templates/24/243e511257f7779fdec8595e74f3c3a7.php(374): Twig\Template->displayBlock()
#32 website.com/vendor/twig/twig/src/Template.php(171): __TwigTemplate_2ca8fd43835316cf29a72e0b834d2972->block_body()
#33 website.com/storage/runtime/compiled_templates/c4/c4fb885dd6dc8e8b6613bbe2410e1ffb.php(94): Twig\Template->displayBlock()
#34 website.com/vendor/twig/twig/src/Template.php(394): __TwigTemplate_121c7b07c8b6c6d0203cb87fefc0fc6d->doDisplay()
#35 website.com/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#36 website.com/storage/runtime/compiled_templates/0d/0de25dabdeb7bcebaecf4f742a32178d.php(56): Twig\Template->display()
#37 website.com/vendor/twig/twig/src/Template.php(394): __TwigTemplate_4efbefcdb39d4023f4396bb2f374d246->doDisplay()
#38 website.com/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#39 website.com/storage/runtime/compiled_templates/24/243e511257f7779fdec8595e74f3c3a7.php(179): Twig\Template->display()
#40 website.com/vendor/twig/twig/src/Template.php(394): __TwigTemplate_2ca8fd43835316cf29a72e0b834d2972->doDisplay()
#41 website.com/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#42 website.com/storage/runtime/compiled_templates/0c/0c5d3db4539362a4f5206d5e01455e22.php(56): Twig\Template->display()
#43 website.com/vendor/twig/twig/src/Template.php(394): __TwigTemplate_5492fdda9b1f59d9d8e189b3225714cb->doDisplay()
#44 website.com/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#45 website.com/vendor/twig/twig/src/Template.php(379): Twig\Template->display()
#46 website.com/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render()
#47 website.com/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render()
#48 website.com/vendor/craftcms/cms/src/web/View.php(451): Twig\Environment->render()
#49 website.com/vendor/craftcms/cms/src/web/View.php(504): craft\web\View->renderTemplate()
#50 website.com/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(56): craft\web\View->renderPageTemplate()
#51 website.com/vendor/yiisoft/yii2/web/Response.php(1098): craft\web\TemplateResponseFormatter->format()
#52 website.com/vendor/craftcms/cms/src/web/Response.php(286): yii\web\Response->prepare()
#53 website.com/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#54 website.com/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#55 website.com/web/index.php(12): yii\base\Application->run()
#56 {main}`

**Comment by ryssbowh** [comment]
Hi,

I doubt that would come from those changes, and I can't reproduce this.
Any chance you can send your database to support@puzzlers.run ?
