### ISSUE TITLE
Export: Key "id" for array with keys "handler, data" does not exist.

### ISSUE THREAD

**Issue by stigzelm** [ryssbowh/craft-activity#12]
Craft version: 4.3.8.2
User activity: 2.3.4

When doing an export I get this error: Key "id" for array with keys "handler, data" does not exist.

Twig\Error\RuntimeError: Key "id" for array with keys "handler, data" does not exist. in /Users/martinstigzelius/Sites/tactotek-online/vendor/ryssbowh/craft-activity/src/templates/field-handlers/plaintext-field.twig:5
Stack trace:
#0 /Users/martinstigzelius/Sites/tactotek-online/vendor/craftcms/cms/src/helpers/Template.php(110): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Array, 'id', Array, 'any', false, false)
#1 /Users/martinstigzelius/Sites/tactotek-online/storage/runtime/compiled_templates/04/0416b2a509901c23ad3afdaf39a611a9fffb9134059a79f95968f8e3396ab8c0.php(112): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Array, 'id', Array)
#2 /Users/martinstigzelius/Sites/tactotek-online/vendor/twig/twig/src/Extension/CoreExtension.php(1202): __TwigTemplate_ea8455a9779aade3256b8a2e14ecafceda80550bba2180360f0a4cf8264ab3e5->macro_textFromValue(Array)
#3 /Users/martinstigzelius/Sites/tactotek-online/storage/runtime/compiled_templates/04/0416b2a509901c23ad3afdaf39a611a9fffb9134059a79f95968f8e3396ab8c0.php(62): twig_call_macro(Object(__TwigTemplate_ea8455a9779aade3256b8a2e14ecafceda80550bba2180360f0a4cf8264ab3e5), 'macro_textFromV...', Array, 25, Array, Object(Twig\Source))
#4 /Users/martinstigzelius/Sites/tactotek-online/vendor/twig/twig/src/Template.php(394): __TwigTemplate_ea8455a9779aade3256b8a2e14ecafceda80550bba2180360f0a4cf8264ab3e5->doDisplay(Array, Array)
#5 /Users/martinstigzelius/Sites/tactotek-online/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#6 /Users/martinstigzelius/Sites/tactotek-online/storage/runtime/compiled_templates/c4/c471dfde439b9fd9f90ae03c58130edfbd21986868a6f910fec4af9307bfa321.php(372): Twig\Template->display(Array)
#7 /Users/martinstigzelius/Sites/tactotek-online/vendor/twig/twig/src/Extension/CoreExtension.php(1202): __TwigTemplate_454aca77d23f75002531e69bea50338280d943a0e9f1607405d6cd4214cc4ca2->macro_elementField(Array, Array)
#8 /Users/martinstigzelius/Sites/tactotek-online/storage/runtime/compiled_templates/b7/b7352edbe8bfa89e4efefab5f2e0f146105e2cca4c23d71444523068242b3a34.php(88): twig_call_macro(Object(__TwigTemplate_454aca77d23f75002531e69bea50338280d943a0e9f1607405d6cd4214cc4ca2), 'macro_elementFi...', Array, 19, Array, Object(Twig\Source))
#9 /Users/martinstigzelius/Sites/tactotek-online/vendor/twig/twig/src/Template.php(394): __TwigTemplate_cd43abf749353324de3b580e8f94db1a97db650185a80588e24b715821b4eae3->doDisplay(Array, Array)
#10 /Users/martinstigzelius/Sites/tactotek-online/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#11 /Users/martinstigzelius/Sites/tactotek-online/storage/runtime/compiled_templates/c4/c471dfde439b9fd9f90ae03c58130edfbd21986868a6f910fec4af9307bfa321.php(372): Twig\Template->display(Array)
#12 /Users/martinstigzelius/Sites/tactotek-online/vendor/twig/twig/src/Extension/CoreExtension.php(1202): __TwigTemplate_454aca77d23f75002531e69bea50338280d943a0e9f1607405d6cd4214cc4ca2->macro_elementField(Object(Ryssbowh\Activity\models\ChangedField))
#13 /Users/martinstigzelius/Sites/tactotek-online/storage/runtime/compiled_templates/56/56d31333172a4ce5fc7938fa1f19bc1679ae0862c2a7cb254b5284c0aa8d6741.php(53): twig_call_macro(Object(__TwigTemplate_454aca77d23f75002531e69bea50338280d943a0e9f1607405d6cd4214cc4ca2), 'macro_elementFi...', Array, 6, Array, Object(Twig\Source))
#14 /Users/martinstigzelius/Sites/tactotek-online/vendor/twig/twig/src/Template.php(394): __TwigTemplate_e945174f52c3a0ded9ff8da585ce3f3377ed2cec37de9b7061ce416ebd386764->doDisplay(Array, Array)
#15 /Users/martinstigzelius/Sites/tactotek-online/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#16 /Users/martinstigzelius/Sites/tactotek-online/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#17 /Users/martinstigzelius/Sites/tactotek-online/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#18 /Users/martinstigzelius/Sites/tactotek-online/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#19 /Users/martinstigzelius/Sites/tactotek-online/vendor/craftcms/cms/src/web/View.php(451): Twig\Environment->render('activity/descri...', Array)
#20 /Users/martinstigzelius/Sites/tactotek-online/vendor/ryssbowh/craft-activity/src/base/logs/ElementLog.php(35): craft\web\View->renderTemplate('activity/descri...', Array)
#21 /Users/martinstigzelius/Sites/tactotek-online/vendor/yiisoft/yii2/base/Component.php(139): Ryssbowh\Activity\base\logs\ElementLog->getDescription()
#22 /Users/martinstigzelius/Sites/tactotek-online/vendor/ryssbowh/craft-activity/src/exporters/Text.php(38): yii\base\Component->__get('description')
#23 /Users/martinstigzelius/Sites/tactotek-online/vendor/ryssbowh/craft-activity/src/controllers/ExportController.php(26): Ryssbowh\Activity\exporters\Text->getExportContent(Array)
#24 [internal function]: Ryssbowh\Activity\controllers\ExportController->actionIndex()
#25 /Users/martinstigzelius/Sites/tactotek-online/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#26 /Users/martinstigzelius/Sites/tactotek-online/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#27 /Users/martinstigzelius/Sites/tactotek-online/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#28 /Users/martinstigzelius/Sites/tactotek-online/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('activity/export', Array)
#29 /Users/martinstigzelius/Sites/tactotek-online/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('activity/export', Array)
#30 /Users/martinstigzelius/Sites/tactotek-online/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#31 /Users/martinstigzelius/Sites/tactotek-online/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#32 /Users/martinstigzelius/Sites/tactotek-online/web/index.php(22): yii\base\Application->run()
#33 /Users/martinstigzelius/.composer/vendor/laravel/valet/server.php(235): require('/Users/martinst...')
#34 {main}

**Comment by ryssbowh** [comment]
Thanks for reporting.
I found a few issues for nested long text fields (Plain Text or Redactor within a Neo/Matrix/SuperTable field).
That should be fixed for you in 2.3.5

**Comment by stigzelm** [comment]
Ok, Thanks for taking a look so quickly. I update User Activity to the version 2.3.5. Now when I try to export Text, I get a new error:

### Getting unknown property: Ryssbowh\Activity\exporters\Text::user_name

yii\base\UnknownPropertyException: Getting unknown property: Ryssbowh\Activity\exporters\Text::user_name in /Users/martinstigzelius/Sites/tactotek-online/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /Users/martinstigzelius/Sites/tactotek-online/vendor/ryssbowh/craft-activity/src/exporters/Text.php(79): yii\base\Component->__get('user_name')
#1 /Users/martinstigzelius/Sites/tactotek-online/vendor/ryssbowh/craft-activity/src/exporters/Text.php(37): Ryssbowh\Activity\exporters\Text->getUserName(Object(Ryssbowh\Activity\models\logs\users\UserLoggedIn))
#2 /Users/martinstigzelius/Sites/tactotek-online/vendor/ryssbowh/craft-activity/src/controllers/ExportController.php(27): Ryssbowh\Activity\exporters\Text->getExportContent(Array)
#3 [internal function]: Ryssbowh\Activity\controllers\ExportController->actionIndex()
#4 /Users/martinstigzelius/Sites/tactotek-online/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /Users/martinstigzelius/Sites/tactotek-online/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#6 /Users/martinstigzelius/Sites/tactotek-online/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#7 /Users/martinstigzelius/Sites/tactotek-online/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('activity/export', Array)
#8 /Users/martinstigzelius/Sites/tactotek-online/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('activity/export', Array)
#9 /Users/martinstigzelius/Sites/tactotek-online/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#10 /Users/martinstigzelius/Sites/tactotek-online/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#11 /Users/martinstigzelius/Sites/tactotek-online/web/index.php(22): yii\base\Application->run()
#12 /Users/martinstigzelius/.composer/vendor/laravel/valet/server.php(235): require('/Users/martinst...')
#13 {main}

**Comment by ryssbowh** [comment]
Hi,
That's fixed in 2.3.6
