### ISSUE TITLE
[BUG] Changes to the user group are not logged.

### ISSUE THREAD

**Issue by mihob** [ryssbowh/craft-activity#14]
It looks like changes to user groups are not logged. However, the saving itself appears in the log.

Craft Version: 4.4.5
Plugin Version: 2.3.7

**Comment by ryssbowh** [comment]
I've tried this, I'm getting the changes recorded, in config (name, handle, description) and in permissions.
You will get 2 events recorded as they are done at different times by Craft :
- One for the config
- One for the permissions

Either of them could be empty if you didn't make any changes in them.

**Comment by mihob** [comment]
Hello, thank you for your reply. Perhaps I have expressed myself incorrectly.

When I add or remove a group to a user, it is not logged.

Changes to individual permissions are logged correctly.

**Comment by ryssbowh** [comment]
I see,

Fixed it in 2.3.9.

**Comment by mihob** [comment]
Thx! It's working in the actual Version
