### ISSUE TITLE
Globals Set Not Saving

### ISSUE THREAD

**Issue by rezaplus** [ryssbowh/craft-activity#19]
There is a issue with the globals in latest version. When I try to update globals, I receive a "Globals set saved" notice, but the changes are not reflected, and the globals remain unchanged.

I tested this issue with plugin version 2.3.13, and the problem did not occur.

**Comment by ryssbowh** [comment]
Hi @rezaplus can you detail which fields you have on this globals ?

**Comment by rezaplus** [comment]
Hi
All field types aren't updated; newly created fields work well, but the old fields aren't updated.

**Comment by ryssbowh** [comment]
Hi,
Can you please share the types of fields you have on this global. I can't reproduce this.
Or better if you could send a database dump to info@webpuzzlers.co.uk ?

**Comment by rezaplus** [comment]
Unfortunately, I cannot provide access to the database. I have thoroughly tested various field types, and none of them seem to be functioning correctly. Please review the changes made in this [commit](https://github.com/ryssbowh/craft-activity/commit/2fc22bf28f75200aadeb577e5ccbe4182b9f9faf)

**Comment by ryssbowh** [comment]
@rezaplus Can you at least share your logs ?
And also please provide a list of the other plugins you have, it may be related to eager loading but I still can't reproduce it.
Also, do you operate multi sites ?

**Comment by ryssbowh** [comment]
Can you also try 2.3.15, I'm not sure what is your issue is but that sounds related

**Comment by rezaplus** [comment]
It works well, Thank you
