### ISSUE TITLE
Error after saving fields and entry types

### ISSUE THREAD

**Issue by james-at-klik** [ryssbowh/craft-activity#2]
Hi there,

I'm getting the following error after saving fields and entry types:

TypeError
Argument 2 passed to Ryssbowh\Activity\base\recorders\ConfigModelRecorder::typeValue() must be an instance of Ryssbowh\Activity\traits\mixed, string given, called in /home/(username)/vendor/ryssbowh/craft-activity/src/traits/ProjectConfigFields.php on line 45

Fields/entries get saved successfully, the error seems to happen afterwards.

PHP 7.4.32
Craft Pro 3.7.58

Plugins
Element Relations 1.0.6
Freeform 3.13.7
Redactor 2.10.10
SEO 3.7.4
User Activity 1.1.0

Stack trace attached.
Thanks for your time.

[stacktrace.txt](https://github.com/ryssbowh/craft-activity/files/9875335/stacktrace.txt)

**Comment by ryssbowh** [comment]
Thanks for reporting, I fixed this in 1.1.1

**Comment by james-at-klik** [comment]
Thanks for the quick response! 

Updated to version 1.1.1

There seems to be another similar issue on a different line:

TypeError: Return value of Ryssbowh\Activity\base\recorders\ConfigModelRecorder::typeValue() must be an instance of Ryssbowh\Activity\traits\mixed, string returned in /home/(username)/vendor/ryssbowh/craft-activity/src/traits/ProjectConfigFields.php:108

Stack trace is pretty much the same as previous.

Thanks for your time.

**Comment by ryssbowh** [comment]
Ha sorry, forgot one.
Released 1.1.2 just now

**Comment by james-at-klik** [comment]
Thank you :)

No issues to report with 1.1.2
