### ISSUE TITLE
Error Saving Entry | 1406 Data too long for column 'data' at row 1

### ISSUE THREAD

**Issue by spAnser** [ryssbowh/craft-activity#23]
```
Database Exception – [yii\db\Exception](https://www.yiiframework.com/doc-2.0/yii-db-exception.html)
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'data' at row 1
The SQL being executed was: INSERT INTO `activity_changed_fields` (`log_id`, `name`, `handler`, `data`, `dateCreated`, `dateUpdated`, `uid`) VALUES
```

This entry has a neo field and adding a block above a good number of other blocks generates a change list that is apparently to big to save in the database.

**Comment by ryssbowh** [comment]
Thanks for reporting,

There was an issue calculating neo block changes which caused all the blocks to be logged, I've fixed that along with changing the column type to allow more content just in case.

This is released for craft 4 & 5 just now
