### ISSUE TITLE
Element Title null

### ISSUE THREAD

**Issue by mlebarron** [ryssbowh/craft-activity#26]
```
Ryssbowh\Activity\base\logs\ElementLog::getElementTitle(): Return value must be of type string, null returned
```

Editing a regular entry on my site results in database entries that appear to not have a `target_name` resulting in viewing the activity list throwing the above error. 

It's not clear to me if the issue is in the saving of the activity log and there should always be a `target_name` or if the function needs to account for a `null` value. 

I can provide data samples if it helps. I'm using Craft 5 and plugin version 3.0.1

**Comment by ryssbowh** [comment]
Hi @mlebarron the target_name should be populated if you're looking at an Element.
Could you maybe send the content of your activity_logs table to info@webpuzzlers.co.uk ?
The stack trace would also be helpful if you have it.

**Comment by mlebarron** [comment]
@ryssbowh emailed the table and stack trace. LMK if you need anything else
