### ISSUE TITLE
Error when updating field instructions within entry types or matrix blocks - Undefined array key "instructions" in FieldLayout.php

### ISSUE THREAD

**Issue by chaseburklund** [ryssbowh/craft-activity#29]
Description:
An error occurs specifically when updating a field’s instructions (other than the title) within an entry type or a new block/matrix block. Initially, I can add a field with instructions to an entry type or block without issue and save. However, when I attempt to update the field’s instructions within the same entry type or block and save again, an error is thrown. The User Activity Plugin throws an Undefined array key "instructions" error, suggesting that the "instructions" key may not be defined in certain scenarios.

Steps to Reproduce:
- Add a field with instructions to an entry type or matrix block and save it. (This works fine.)
- Edit the field's instructions within the same entry type or block and attempt to save.
- An error is thrown, preventing the save operation

Error Message:
`yii\base\ErrorException: Undefined array key "instructions" in /var/www/html/backend/vendor/ryssbowh/craft-activity/src/models/fieldHandlers/projectConfig/FieldLayout.php:118`
![image](https://github.com/user-attachments/assets/3ea61744-7125-4de2-96e2-d01f8306cbe0)

Additional Details:
- Craft CMS version: 4.12.8
- Plugin version: 2.4.3
- PHP version: 8.1.3

**Comment by ryssbowh** [comment]
Thanks for reporting, this has been fixed in 2.5.0
