### ISSUE TITLE
Ability to Export Logs

### ISSUE THREAD

**Issue by brianrivet-tilt** [ryssbowh/craft-activity#7]
Hi,

This is to open a discussion about a new feature - exporting logs to a file

The use case for this is situations where a longer -term record of the logs might be needed for regulatory purposes like with a banking site, or something like that. Being able to export the logs to a text log file for longer term storage than what would be kept in the site database would be a nice feature.

**Comment by ryssbowh** [comment]
Exporting a date - title- user name to a file, let's say CSV for example is simple, I can add that easily.
Exporting changed fields is going to be more difficult, csv is not really appropriate for this kind of data. Did you also have in mind to export the changed fields ?

**Comment by brianrivet-tilt** [comment]
Ideally it would be good to have a log of field changes as well. I'm not necessarily thinking anything too complex though.  For instance, in looking at the screen shots on the plugin page in the Craft plugin store, the info shown in screen shots 1 and 4 would be plenty. If it can be done either as a csv or as a straight text file representation of what is shown in those screens that is really all we'd be looking for. Just a record in a file of what happened so that it can be kept long-term rather than being kept in the site database and having it expire after a certain length of time.  If we could set something like that up to output a log file maybe once a week with the activity of the previous week and do it via a cron job that would be perfect.

**Comment by ryssbowh** [comment]
Sure, will look into this

**Comment by ryssbowh** [comment]
@brianrivet-tilt This is now out for Craft 4 (version 2.3.0), I've added a text and pdf exporters.
Will port this to Craft 3 shortly.
https://puzzlers.run/plugins/user-activity/2.x/usage#export
