### ISSUE TITLE
Show user full name instead of friendly name

### ISSUE THREAD

**Issue by green17** [ryssbowh/craft-activity#9]
Would it be possible to show the user's full name instead of their friendly name? In the main dashboard view (and the dropdown filter) it can get very confusing when you have a lot of admin users and many have the same first name.

**Comment by ryssbowh** [comment]
Yes makes sense.

I added this to 1.3.2 and 2.3.2 as a setting (off by default).

Note that all data saved for users that are currently deleted will still contain the friendly name.
